### ISSUE TITLE
Second derivative uses quotation mark, not double prime

### ISSUE THREAD

**Issue by perey** [nadvornix/calculus-made-easy#1]
https://github.com/nadvornix/calculus-made-easy/blob/03bf20ad848eb19b74e7c1cd775b01baf173f88b/3.html#L273

This second derivative is notated with the character ” (U+201D RIGHT DOUBLE QUOTATION MARK). It should be using a double prime instead.

I believe that the usual way to do this with MathJax is to just use a pair of '' characters (U+0027 APOSTROPHE). Alternatively, ″ (U+2033 DOUBLE PRIME) is also available and should work.

**Comment by nadvornix** [comment]
Fixed. Quick grep showed same problem also in chapters 3, 7, 16. Thanks for a great bug report. I will be glad for any other suggestions.
