### ISSUE TITLE
Link appearing as markup

### ISSUE THREAD

**Issue by perey** [nadvornix/calculus-made-easy#2]
https://github.com/nadvornix/calculus-made-easy/blob/d140375d8c58d08c5becdb0457b7460f3385e665/6.html#L59

The "Pageref" markup in this line is evidently meant to produce a link, but is appearing literally in the text. Both the Gutenberg text, and a PDF of a scanned original, have it linking to the ["Note to Chapter III."](https://github.com/nadvornix/calculus-made-easy/blob/f7786d47cd0d31bf1804cc11b9d6bb84b550ce57/3.html#L242)

**Comment by nadvornix** [comment]
Fixed. Thanks! Keep them coming :-)
