### ISSUE TITLE
MathBlog links not working

### ISSUE THREAD

**Issue by rjmeats** [nadvornix/calculus-made-easy#9]
The two *MathBlog* links in the index.html page aren't working.

They refer to *math-blog.com* instead of *mathblog.com*. 

https://mathblog.com/mathematics-books/

**Comment by nadvornix** [comment]
Thanks. Fixed.
(Interesting.. It used to work. They seem to change their domain..)

**Comment by rjmeats** [comment]
Thanks.

A bit of googling confirmed the original domain name. 

Antonio Cangiano, the *MathBlog* creator, references the hyphenated math-blog.com domain name in his book *Technical Blogging*, and even discusses the reason for its hyphen. 

See https://technicalblogging.com/choosing-a-domain-name-for-your-blog/
